model_specification:
  # Features
  features_to_drop:
    - facebook_I
    - search_clicks_P
    # - competitor_sales_B
    # - t
    # - day_of_year

  date_column: date_week

  objective_variable: revenue

  channel_columns:
    - tv_S
    - ooh_S
    - print_S
    # - facebook_I
    # - search_clicks_P
    - search_S
    - facebook_S
    - newsletter

  control_columns:
    - events
    # - competitor_sales_B
    - day_of_year
    - t

  # Model Configuration
  adstock_max_lag: 8

  model_config:
    alpha:
      dist: Beta
      kwargs:
        alpha: 1
        beta: 3
    beta_channel:
      dist: HalfNormal
      kwargs:
        sigma: 2
    gamma_control:
      dist: Normal
      kwargs:
        mu: 0
        sigma: 2
    gamma_fourier:
      dist: Laplace
      kwargs:
        b: 1
        mu: 0
    intercept:
      dist: Normal
      kwargs:
        mu: 0
        sigma: 2
    lam:
      dist: Gamma
      kwargs:
        alpha: 3
        beta: 1
    likelihood:
      dist: Normal
      kwargs:
        sigma:
          dist: HalfNormal
          kwargs:
            sigma: 2

  validate_data: true

  yearly_seasonality: 1

  # Sampler Configuration
  sampler_config:
    progressbar: true
    nuts_sampler: numpyro
    draws: 2000
    target_accept: 0.95
    chains: 4
    random_seed: 123
